export const emailHtml = ({
  name,
  mappedCartItems,
  amount_discount,
  amount_shipping,
  amount_subtotal,
  amount_tax,
  amount_total,
  order_no,
  order_date,
  shipping_details,
  customer_details,
}) => {
  return `
    <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
    <html xmlns="http://www.w3.org/1999/xhtml" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office">  
    <head>
      <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="format-detection" content="telephone=no">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title></title>      
      <style type="text/css" emogrify="no">#outlook a { padding:0; } .ExternalClass { width:100%; } .ExternalClass, .ExternalClass p, .ExternalClass span, .ExternalClass font, .ExternalClass td, .ExternalClass div { line-height: 100%; } table td { border-collapse: collapse; mso-line-height-rule: exactly; } .editable.image { font-size: 0 !important; line-height: 0 !important; } .nl2go_preheader { display: none !important; mso-hide:all !important; mso-line-height-rule: exactly; visibility: hidden !important; line-height: 0px !important; font-size: 0px !important; } body { width:100% !important; -webkit-text-size-adjust:100%; -ms-text-size-adjust:100%; margin:0; padding:0; } img { outline:none; text-decoration:none; -ms-interpolation-mode: bicubic; } a img { border:none; } table { border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; } th { font-weight: normal; text-align: left; } *[class="gmail-fix"] { display: none !important; } </style>      
      <style type="text/css" emogrify="no"> @media (max-width: 600px) { .gmx-killpill { content: ' /03D1';} } </style>
      <style type="text/css" emogrify="no">
        @media (max-width: 600px) {
           .gmx-killpill { content: ' /03D1';} 
           .r0-o { border-style: solid !important; margin: 0 auto 0 auto !important; width: 100% !important } 
           .r1-i { background-color: #5d695f !important } 
           .r2-c { box-sizing: border-box !important; text-align: center !important; valign: top !important; width: 320px !important } 
           .r3-o { border-style: solid !important; margin: 0 auto 0 auto !important; width: 450px !important } 
           .r4-i { padding-bottom: 31px !important; padding-left: 10px !important; padding-right: 10px !important; padding-top: 31px !important } 
           .r5-c { box-sizing: border-box !important; display: block !important; valign: top !important; width: 100% !important } 
           .r6-o { border-style: solid !important; width: 100% !important } 
           .r7-o { border-style: solid !important; margin: 0 auto 0 auto !important; width: 165px !important } 
           .r8-i { background-color: #5d695f !important } 
           .r9-c { box-sizing: border-box !important; text-align: center !important; valign: top !important; width: 100% !important } 
           .r10-i { background-color: #fcf6ea !important; padding-left: 15px !important; padding-right: 15px !important; padding-top: 76px !important } 
           .r11-o { border-style: solid !important; margin: 0 auto 0 0 !important; margin-bottom: 0px !important; margin-top: 0px !important; width: 100% !important } 
           .r12-i { text-align: left !important } 
           .r13-o { border-style: solid !important; margin: 0 auto 0 0 !important; width: 100% !important } 
           .r14-i { padding-top: 15px !important; text-align: left !important } 
           .r15-i { background-color: #fcf6ea !important; padding-bottom: 70px !important; padding-left: 15px !important; padding-right: 15px !important; padding-top: 45px !important } 
           .r16-i { padding-left: 0px !important; padding-right: 0px !important } 
           .r17-c { box-sizing: border-box !important; padding-top: 10px !important; text-align: left !important; valign: top !important; width: 100% !important } 
           .r18-c { box-sizing: border-box !important; padding: 0 !important; text-align: left !important; valign: top !important; width: 100% !important } 
           .r19-o { border-style: solid !important; margin: 0 auto 0 0 !important; margin-top: 40px !important; width: 100% !important } 
           .r20-i { padding: 0 !important; text-align: center !important } 
           .r21-r { background-color: #121212 !important; border-radius: 0px !important; border-width: 0px !important; box-sizing: border-box; height: initial !important; padding: 0 !important; padding-bottom: 14px !important; padding-left: 5px !important; padding-right: 5px !important; padding-top: 13px !important; text-align: center !important; width: 100% !important } 
           .r22-o { border-style: solid !important; margin: 0 auto 0 0 !important; margin-top: 20px !important; width: 100% !important } 
           .r23-r { background-color: #5d695f !important; border-color: #121212 !important; border-radius: 0px !important; border-width: 2px !important; box-sizing: border-box; height: initial !important; padding: 0 !important; padding-bottom: 12px !important; padding-left: 5px !important; padding-right: 5px !important; padding-top: 12px !important; text-align: center !important; width: 100% !important } 
           .r24-o { border-style: solid !important; margin: 0 0 0 auto !important; width: 100% !important } 
           .r25-i { padding-top: 30px !important } 
           .r26-i { background-color: #976952 !important; padding-bottom: 30px !important; padding-left: 15px !important; padding-right: 15px !important; padding-top: 30px !important } 
           .r27-i { padding-top: 20px !important; text-align: left !important } 
           .r28-i { background-color: #fcf6ea !important; padding-left: 10px !important; padding-right: 10px !important; padding-top: 57px !important } 
           .r29-c { box-sizing: border-box !important; text-align: center !important; valign: top !important; width: 124px !important } 
           .r30-o { border-style: solid !important; margin: 0 auto 0 auto !important; width: 124px !important } 
           .r31-c { box-sizing: border-box !important; text-align: left !important; valign: top !important; width: 100% !important } 
           .r32-o { border-style: solid !important; margin: 0 auto 0 0 !important; margin-top: 25px !important; width: 100% !important } 
           .r33-i { padding-top: 30px !important; text-align: center !important } 
           .r34-c { box-sizing: border-box !important; padding-top: 6px !important; text-align: center !important; valign: top !important; width: 100% !important } 
           .r35-i { padding-top: 20px !important; text-align: center !important } 
           .r36-i { background-color: #fcf6ea !important; padding-left: 10px !important; padding-right: 10px !important; padding-top: 30px !important } 
           .r37-i { background-color: #fcf6ea !important; padding-left: 15px !important; padding-right: 15px !important; padding-top: 30px !important } 
           .r38-i { background-color: #fcf6ea !important; padding-left: 15px !important; padding-right: 15px !important; padding-top: 18px !important } 
           .r39-c { box-sizing: border-box !important; valign: top !important; width: 50% !important } 
           .r40-i { text-align: right !important } 
           .r41-i { background-color: #fcf6ea !important; padding-left: 15px !important; padding-right: 15px !important; padding-top: 11px !important } 
           .r42-i { background-color: #fcf6ea !important; padding-left: 15px !important; padding-right: 15px !important; padding-top: 9px !important } 
           .r43-i { background-color: #fcf6ea !important; padding-bottom: 55px !important; padding-left: 15px !important; padding-right: 15px !important; padding-top: 15px !important } 
           .r44-o { background-size: cover !important; border-style: solid !important; margin: 0 auto 0 auto !important; width: 100% !important } 
           .r45-i { background-color: #976952 !important; padding-left: 15px !important; padding-right: 15px !important; padding-top: 55px !important } 
           .r46-c { box-sizing: border-box !important; valign: top !important; width: 100% !important } 
           .r47-c { box-sizing: border-box !important; text-align: center !important; width: 100% !important } 
           .r48-c { box-sizing: border-box !important; width: 100% !important } 
           .r49-i { font-size: 0px !important; padding-left: 93px !important; padding-right: 93px !important } 
           .r50-c { box-sizing: border-box !important; width: 32px !important } 
           .r51-o { border-style: solid !important; margin-right: 20px !important; width: 32px !important } 
           .r52-i { padding-bottom: 5px !important; padding-top: 5px !important } 
           .r53-i { background-color: #976952 !important; padding-left: 15px !important; padding-right: 15px !important; padding-top: 48px !important } 
           .r54-i { background-color: #976952 !important; padding-bottom: 45px !important; padding-left: 15px !important; padding-right: 15px !important; padding-top: 23px !important } 
           .r55-i { padding-top: 5px !important; text-align: left !important } body { -webkit-text-size-adjust: none } 
           .nl2go-responsive-hide { display: none } 
           .nl2go-body-table { min-width: unset !important } 
           .mobshow { height: auto !important; overflow: visible !important; max-height: unset !important; visibility: visible !important; border: none !important } 
           .resp-table { display: inline-table !important } 
           .magic-resp { display: table-cell !important } 
          } 
      </style>
      <!--[if !mso]><!-->
      <style type="text/css" emogrify="no">@import url("https://fonts.googleapis.com/css2?family=Montserrat"); </style>
      <!--<![endif]-->
      <style type="text/css">
        p, h1, h2, h3, h4, ol, ul, li { margin: 0; } 
        a, a:link { color: #9c71f0; text-decoration: none } 
        .nl2go-default-textstyle { color: #3b3f44; font-family: Montserrat, arial,helvetica,sans-serif; font-size: 16px; line-height: 1.2; word-break: break-word } 
        .default-button { color: #3b3f44; font-family: Montserrat, arial,helvetica,sans-serif; font-size: 16px; font-style: normal; font-weight: normal; line-height: 1.15; text-decoration: none; word-break: break-word } 
        .sib_class_16_white_roboto { color: #FFFFFF; font-family: Montserrat, arial,helvetica,sans-serif; font-size: 16px; word-break: break-word } 
        .sib_class_16_black { color: #000000; font-family: Montserrat, arial,helvetica,sans-serif; font-size: 16px; word-break: break-word } 
        .sib_class_16_white { color: #ffffff; font-family: Montserrat, arial,helvetica,sans-serif; font-size: 16px; word-break: break-word } 
        .sib_class_16_black_sb { color: #000000; font-family: Montserrat, arial,helvetica,sans-serif; font-size: 16px; font-weight: 600; word-break: break-word } 
        .sib_class_16_black_b { color: #000000; font-family: Montserrat, arial,helvetica,sans-serif; font-size: 16px; font-weight: 700; word-break: break-word } 
        .sib_class_18_black_sb { color: #000000; font-family: Montserrat, arial,helvetica,sans-serif; font-size: 18px; font-weight: 600; word-break: break-word } 
        .sib_class_18_blue_sb { color: #75EBEF; font-family: Montserrat, arial,helvetica,sans-serif; font-size: 18px; font-weight: 600; word-break: break-word } 
        .sib_class_20_black_roboto { color: #000000; font-family: Montserrat, arial,helvetica,sans-serif; font-size: 20px; word-break: break-word } 
        .sib_class_20_black_b { color: #000000; font-family: Montserrat, arial,helvetica,sans-serif; font-size: 20px; font-weight: 700; word-break: break-word } 
        .sib_class_20_black_b_ul { color: #000000; font-family: Montserrat, arial,helvetica,sans-serif; font-size: 20px; font-weight: 700; text-decoration: underline; word-break: break-word } 
        .sib_class_20_white_b_ul { color: #ffffff; font-family: Montserrat, arial,helvetica,sans-serif; font-size: 20px; font-weight: 700; text-decoration: underline; word-break: break-word } 
        .sib_class_24_black_b { color: #000000; font-family: Montserrat, arial,helvetica,sans-serif; font-size: 24px; font-weight: 700; word-break: break-word } 
        .sib_class_30_black_sb { color: #000000; font-family: Montserrat, arial,helvetica,sans-serif; font-size: 30px; font-weight: 600; word-break: break-word } 
        .default-heading1 { color: #000000; font-family: Montserrat, arial,helvetica,sans-serif; font-size: 30px; word-break: break-word } 
        .default-heading2 { color: #ffffff; font-family: Montserrat, arial,helvetica,sans-serif; font-size: 20px; word-break: break-word } 
        .default-heading3 { color: #000000; font-family: Montserrat, arial,helvetica,sans-serif; font-size: 20px; word-break: break-word } 
        .default-heading4 { color: #000000; font-family: Montserrat, arial,helvetica,sans-serif; font-size: 18px; word-break: break-word } 
        a[x-apple-data-detectors] { color: inherit !important; text-decoration: inherit !important; font-size: inherit !important; font-family: inherit !important; font-weight: inherit !important; line-height: inherit !important; } 
        .no-show-for-you { border: none; display: none; float: none; font-size: 0; height: 0; line-height: 0; max-height: 0; mso-hide: all; overflow: hidden; table-layout: fixed; visibility: hidden; width: 0; } 
      </style>
      <!--[if mso]><xml> 
      <o:OfficeDocumentSettings> <o:AllowPNG/> 
      <o:PixelsPerInch>96</o:PixelsPerInch> </o:OfficeDocumentSettings> 
      </xml><![endif]-->
      <style type="text/css">a:link{color: #9c71f0; text-decoration: none;}
      </style>
    </head>      
    <body bgcolor="#9c71f0" text="#3b3f44" link="#9c71f0" yahoo="fix" style="background-color: #5d695f;">
      <table cellspacing="0" cellpadding="0" border="0" role="presentation" class="nl2go-body-table" width="100%" style="background-color: #5d695f; width: 100%;">
      <tr><td> <table cellspacing="0" cellpadding="0" border="0" role="presentation" width="100%" align="center" class="r0-o" style="table-layout: fixed; width: 100%;"><tr><td valign="top" class="r1-i" style="background-color: #5d695f;"> <table cellspacing="0" cellpadding="0" border="0" role="presentation" width="600" align="center" class="r3-o" style="table-layout: fixed; width: 600px;"><tr><td class="r4-i" style="padding-bottom: 31px; padding-left: 10px; padding-right: 10px; padding-top: 31px;"> <table width="100%" cellspacing="0" cellpadding="0" border="0" role="presentation"><tr><th width="100%" valign="top" class="r5-c" style="font-weight: normal;"> <table cellspacing="0" cellpadding="0" border="0" role="presentation" width="165" align="center" class="r7-o" style="table-layout: fixed; width: 165px;"><tr><td style="font-size: 0px; line-height: 0px;"> <a href="https://terhire.com" target="_blank" style="color: #9c71f0; text-decoration: none;"><img src="https://res.cloudinary.com/diiohnshc/image/upload/v1712400750/Terhire/Terhire_1_fb9bju.png" width="165" border="0" style="display: block; width: 100%;"></td> </tr></table></th> </tr></table></td> </tr></table></td> </tr></table><table cellspacing="0" cellpadding="0" border="0" role="presentation" width="600" align="center" class="r3-o" style="table-layout: fixed; width: 750px;"><tr><td valign="top" class="r8-i" style="background-color: #5d695f;"> <table cellspacing="0" cellpadding="0" border="0" role="presentation" width="100%" align="center" class="r0-o" style="table-layout: fixed; width: 100%;"><tr><td class="r10-i" style="background-color: #fcf6ea; padding-left: 35px; padding-right: 35px; padding-top: 76px;"> <table width="100%" cellspacing="0" cellpadding="0" border="0" role="presentation"><tr><th width="100%" valign="top" class="r5-c" style="font-weight: normal;"> <table cellspacing="0" cellpadding="0" border="0" role="presentation" width="100%" align="left" class="r11-o" style="table-layout: fixed; width: 100%;"><tr><td align="left" valign="top" class="r12-i nl2go-default-textstyle" style="color: #3b3f44; font-family: Montserrat,arial,helvetica,sans-serif; font-size: 16px; line-height: 1.2; word-break: break-word; text-align: left;"> <div><h1 class="default-heading1" style="margin: 0; color: #000; font-family: Montserrat,arial,helvetica,sans-serif; font-size: 30px; word-break: break-word;">Thank you ${
        name.split(" ")[0]
      },</h1></div> </td> </tr></table><table cellspacing="0" cellpadding="0" border="0" role="presentation" width="100%" align="left" class="r13-o" style="table-layout: fixed; width: 100%;"><tr><td align="left" valign="top" class="r14-i nl2go-default-textstyle" style="color: #3b3f44; font-family: Montserrat,arial,helvetica,sans-serif; font-size: 16px; line-height: 1.2; word-break: break-word; padding-top: 15px; text-align: left;"> <div><div class="sib_class_20_black_roboto" style="color: #000; font-family: Montserrat,arial,helvetica,sans-serif; font-size: 20px; word-break: break-word;">Thank you for choosing Terhire! Your support means everything to us. Once we've shipped your order you'll receive an email with your shipping confirmation and tracking details. Have any questions? Feel free to reach out to us at support@terhire.com. We're here to assist you!</div></div> </td> </tr></table></th> </tr></table></td> </tr></table><table cellspacing="0" cellpadding="0" border="0" role="presentation" width="100%" align="center" class="r0-o" style="table-layout: fixed; width: 100%;"><tr><td class="r15-i" style="background-color: #fcf6ea; padding-bottom: 70px; padding-left: 35px; padding-right: 35px; padding-top: 45px;"> <table width="100%" cellspacing="0" cellpadding="0" border="0" role="presentation"><tr><th width="50%" valign="top" class="r5-c" style="font-weight: normal;"> <table cellspacing="0" cellpadding="0" border="0" role="presentation" width="100%" class="r6-o" style="table-layout: fixed; width: 100%;"><tr><td valign="top" class="r16-i"> <table width="100%" cellspacing="0" cellpadding="0" border="0" role="presentation"><tr><td class="r17-c nl2go-default-textstyle" align="left" style="color: #3b3f44; font-family: Montserrat,arial,helvetica,sans-serif; font-size: 16px; line-height: 1.2; word-break: break-word; padding-top: 10px; text-align: left; valign: top;"> <div><div class="sib_class_16_black_sb" style="color: #000; font-family: Montserrat,arial,helvetica,sans-serif; font-size: 16px; font-weight: 600; word-break: break-word;">
    Order No: ${order_no}
    </div></div> </td> </tr><tr><td class="r17-c nl2go-default-textstyle" align="left" style="color: #3b3f44; font-family: Montserrat,arial,helvetica,sans-serif; font-size: 16px; line-height: 1.2; word-break: break-word; padding-top: 10px; text-align: left; valign: top;"> <div><div class="sib_class_16_black_sb" style="color: #000; font-family: Montserrat,arial,helvetica,sans-serif; font-size: 16px; font-weight: 600; word-break: break-word;">Order date: ${new Date(
      order_date * 1000
    )}</div></div> </td> </tr><tr><td class="r18-c" align="left" style="align: left; padding-top: 40px; valign: top;"> <table cellspacing="0" cellpadding="0" border="0" role="presentation" width="253" class="r19-o" style="background-color: #121212; border-collapse: separate; border-color: #121212; border-radius: 0px; border-style: solid; border-width: 0px; table-layout: fixed; width: 253px;"><tr><td height="20" align="center" valign="top" class="r20-i nl2go-default-textstyle" style="color: #3b3f44; font-family: Montserrat,arial,helvetica,sans-serif; font-size: 16px; word-break: break-word; background-color: #121212; border-radius: 0px; font-style: normal; line-height: 1.15; padding-bottom: 14px; padding-left: 5px; padding-right: 5px; padding-top: 13px; text-align: center;"> 
  <a href="https://terhire.com/order/${order_no}" class="r21-r default-button" target="_blank" data-btn="1" style="color: #3b3f44; font-family: Montserrat,arial,helvetica,sans-serif; font-size: 16px; font-style: normal; font-weight: normal; line-height: 1.15; text-decoration: none; word-break: break-word; word-wrap: break-word; display: block; -webkit-text-size-adjust: none;"> <span class="sib_class_18_blue_sb" style="color: #75ebef; font-family: Montserrat,arial,helvetica,sans-serif; font-size: 18px; font-weight: 600; word-break: break-word;"><span style="color: #ffffff;">Track your order</span></span></a> </td> </tr></table></td> </tr><tr><td class="r18-c" align="left" style="align: left; padding-top: 20px; valign: top;"> <table cellspacing="0" cellpadding="0" border="0" role="presentation" width="253" class="r22-o" style="background-color: #fcf6ea; border-collapse: separate; border-color: #121212; border-radius: 0px; border-style: solid; border-width: 2px; table-layout: fixed; width: 253px;"><tr><td height="19" align="center" valign="top" class="r20-i nl2go-default-textstyle" style="color: #3b3f44; font-family: Montserrat,arial,helvetica,sans-serif; font-size: 16px; word-break: break-word; background-color: #fcf6ea; border-radius: 0px; font-style: normal; line-height: 1.15; padding-bottom: 12px; padding-left: 5px; padding-right: 5px; padding-top: 12px; text-align: center;"> 
    
  <a href="https://terhire.com/collections" class="r23-r default-button" target="_blank" data-btn="2" style="color: #3b3f44; font-family: Montserrat,arial,helvetica,sans-serif; font-size: 16px; font-style: normal; font-weight: normal; line-height: 1.15; text-decoration: none; word-break: break-word; word-wrap: break-word; display: block; -webkit-text-size-adjust: none;"> <span class="sib_class_18_black_sb" style="color: #000; font-family: Montserrat,arial,helvetica,sans-serif; font-size: 18px; font-weight: 600; word-break: break-word;">Continue shopping</span></a>
 </td> </tr></table></td> </tr></table></td> </tr></table></th>
 <th width="50%" valign="top" class="r5-c" style="font-weight: normal;">
 <table cellspacing="0" cellpadding="0" border="0" role="presentation" width="238" align="right" class="r24-o" style="table-layout: fixed; width: 238px;"><tr><td class="r25-i" style="font-size: 0px; line-height: 0px;"> <img src="https://img.mailinblue.com/2670624/images/rnb/original/5fbe5418424c336384002ee7.png" width="238" border="0" style="display: block; width: 100%;"></td> </tr></table></th> </tr></table></td> </tr></table>
 <table cellspacing="0" cellpadding="0" border="0" role="presentation" width="100%" align="center" class="r0-o" style="table-layout: fixed; width: 100%;"><tr><td class="r26-i" style="background-color: #976952; padding-bottom: 30px; padding-left: 35px; padding-right: 35px; padding-top: 30px;"> 
 <table width="100%" cellspacing="0" cellpadding="0" border="0" role="presentation"><tr><th width="50%" valign="top" class="r5-c" style="font-weight: normal;"> <table cellspacing="0" cellpadding="0" border="0" role="presentation" width="100%" align="left" class="r13-o" style="table-layout: fixed; width: 100%;"><tr><td align="left" valign="top" class="r12-i nl2go-default-textstyle" style="color: #3b3f44; font-family: Montserrat,arial,helvetica,sans-serif; font-size: 16px; line-height: 1.2; word-break: break-word; text-align: left;"> <div><h2 class="default-heading2" style="margin: 0; color: #fff; font-family: Montserrat,arial,helvetica,sans-serif; font-size: 20px; word-break: break-word;"><u>Shipping address:</u></h2></div> </td> </tr></table>
 <table cellspacing="0" cellpadding="0" border="0" role="presentation" width="100%" align="left" class="r13-o" style="table-layout: fixed; width: 100%;"><tr><td align="left" valign="top" class="r14-i nl2go-default-textstyle" style="color: #3b3f44; font-family: Montserrat,arial,helvetica,sans-serif; font-size: 16px; line-height: 1.2; word-break: break-word; padding-top: 15px; text-align: left;"> <div><div class="sib_class_16_white" style="color: #fff; font-family: Montserrat,arial,helvetica,sans-serif; font-size: 16px; word-break: break-word;">${
   shipping_details.name
 }<br> ${
  customer_details.email
}<br> ${
    shipping_details.address.line2
      ? shipping_details.address.line2 + "<br>"
      : ""
  } ${shipping_details.address.line1}<br>
  ${shipping_details.address.postal_code}${" "}${
    shipping_details.address.city
  }<br> ${shipping_details.address.state}${" "}${
    shipping_details.address.country
  }</div></div> </td> </tr></table></th> <th width="50%" valign="top" class="r5-c" style="font-weight: normal;"> <table cellspacing="0" cellpadding="0" border="0" role="presentation" width="100%" align="left" class="r13-o" style="table-layout: fixed; width: 100%;"><tr><td align="left" valign="top" class="r27-i nl2go-default-textstyle" style="color: #3b3f44; font-family: Montserrat,arial,helvetica,sans-serif; font-size: 16px; line-height: 1.2; word-break: break-word; text-align: left;"> <div><h2 class="default-heading2" style="margin: 0; color: #fff; font-family: Montserrat,arial,helvetica,sans-serif; font-size: 20px; word-break: break-word;"><u>Bill info:</u></h2></div> </td> </tr></table><table cellspacing="0" cellpadding="0" border="0" role="presentation" width="100%" align="left" class="r13-o" style="table-layout: fixed; width: 100%;"><tr><td align="left" valign="top" class="r14-i nl2go-default-textstyle" style="color: #3b3f44; font-family: Montserrat,arial,helvetica,sans-serif; font-size: 16px; line-height: 1.2; word-break: break-word; padding-top: 15px; text-align: left;"> <div><div class="sib_class_16_white" style="color: #fff; font-family: Montserrat,arial,helvetica,sans-serif; font-size: 16px; word-break: break-word;">${
    customer_details.name
  }<br> ${
    customer_details.address.line2
      ? customer_details.address.line2 + "<br>"
      : ""
  } ${customer_details.address.line1}<br>
  ${customer_details.address.postal_code}${" "}${
    customer_details.address.city
  }<br> ${customer_details.address.state}${" "}${
    customer_details.address.country
  }</div></div> </td> </tr></table></th> </tr></table></td> </tr></table>

${mappedCartItems}

  <table cellspacing="0" cellpadding="0" border="0" role="presentation" width="100%" align="center" class="r0-o" style="table-layout: fixed; width: 100%;"><tr><td class="r37-i" style="background-color: #fcf6ea; padding-left: 35px; padding-right: 35px; padding-top: 30px;"> <table width="100%" cellspacing="0" cellpadding="0" border="0" role="presentation"><tr><th width="100%" valign="top" class="r5-c" style="font-weight: normal;"> <table cellspacing="0" cellpadding="0" border="0" role="presentation" width="530" align="center" class="r0-o" style="table-layout: fixed;"><tr><td class="" style="height: 2px;"> <table width="100%" cellspacing="0" cellpadding="0" border="0" role="presentation"><tr><td><table width="100%" cellspacing="0" cellpadding="0" border="0" role="presentation" height="2" style="border-top-style: solid; background-clip: border-box; border-top-color: #5d695f; border-top-width: 2px; font-size: 2px; line-height: 2px;"><tr><td height="0" style="font-size: 0px; line-height: 0px;">­</td> </tr></table></td> </tr></table></td> </tr></table></th> </tr></table></td> </tr></table>
  <table cellspacing="0" cellpadding="0" border="0" role="presentation" width="100%" align="center" class="r0-o" style="table-layout: fixed; width: 100%;"><tr><td class="r38-i" style="background-color: #fcf6ea; padding-left: 35px; padding-right: 35px; padding-top: 18px;"> <table width="100%" cellspacing="0" cellpadding="0" border="0" role="presentation"><tr><th width="50%" valign="top" class="r39-c" style="font-weight: normal;"> <table cellspacing="0" cellpadding="0" border="0" role="presentation" width="100%" align="left" class="r13-o" style="table-layout: fixed; width: 100%;"><tr><td align="left" valign="top" class="r12-i nl2go-default-textstyle" style="color: #3b3f44; font-family: Montserrat,arial,helvetica,sans-serif; font-size: 16px; line-height: 1.2; word-break: break-word; text-align: left;"> <div><div class="sib_class_16_black_b" style="color: #000; font-family: Montserrat,arial,helvetica,sans-serif; font-size: 16px; font-weight: 700; word-break: break-word;">Discount</div></div> </td> </tr></table></th> <th width="50%" valign="top" class="r39-c" style="font-weight: normal;"> <table cellspacing="0" cellpadding="0" border="0" role="presentation" width="100%" align="left" class="r13-o" style="table-layout: fixed; width: 100%;"><tr><td align="right" valign="top" class="r40-i nl2go-default-textstyle" style="color: #3b3f44; font-family: Montserrat,arial,helvetica,sans-serif; font-size: 16px; line-height: 1.2; word-break: break-word; text-align: right;"> <div><div class="sib_class_16_black_b" style="color: #000; font-family: Montserrat,arial,helvetica,sans-serif; font-size: 16px; font-weight: 700; word-break: break-word;">
  -$${amount_discount / 100}
  </div></div> </td> </tr></table></th> </tr></table></td> </tr></table><table cellspacing="0" cellpadding="0" border="0" role="presentation" width="100%" align="center" class="r0-o" style="table-layout: fixed; width: 100%;"><tr><td class="r41-i" style="background-color: #fcf6ea; padding-left: 35px; padding-right: 35px; padding-top: 11px;"> <table width="100%" cellspacing="0" cellpadding="0" border="0" role="presentation"><tr><th width="50%" valign="top" class="r39-c" style="font-weight: normal;"> <table cellspacing="0" cellpadding="0" border="0" role="presentation" width="100%" align="left" class="r13-o" style="table-layout: fixed; width: 100%;"><tr><td align="left" valign="top" class="r12-i nl2go-default-textstyle" style="color: #3b3f44; font-family: Montserrat,arial,helvetica,sans-serif; font-size: 16px; line-height: 1.2; word-break: break-word; text-align: left;"> <div><div class="sib_class_16_black_b" style="color: #000; font-family: Montserrat,arial,helvetica,sans-serif; font-size: 16px; font-weight: 700; word-break: break-word;">Subtotal</div></div> </td> </tr></table></th> <th width="50%" valign="top" class="r39-c" style="font-weight: normal;"> <table cellspacing="0" cellpadding="0" border="0" role="presentation" width="100%" align="left" class="r13-o" style="table-layout: fixed; width: 100%;"><tr><td align="right" valign="top" class="r40-i nl2go-default-textstyle" style="color: #3b3f44; font-family: Montserrat,arial,helvetica,sans-serif; font-size: 16px; line-height: 1.2; word-break: break-word; text-align: right;"> <div><div class="sib_class_16_black_b" style="color: #000; font-family: Montserrat,arial,helvetica,sans-serif; font-size: 16px; font-weight: 700; word-break: break-word;">
  $${amount_subtotal / 100}
  </div></div> </td> </tr></table></th> </tr></table></td> </tr></table><table cellspacing="0" cellpadding="0" border="0" role="presentation" width="100%" align="center" class="r0-o" style="table-layout: fixed; width: 100%;"><tr><td class="r41-i" style="background-color: #fcf6ea; padding-left: 35px; padding-right: 35px; padding-top: 11px;"> <table width="100%" cellspacing="0" cellpadding="0" border="0" role="presentation"><tr><th width="50%" valign="top" class="r39-c" style="font-weight: normal;"> <table cellspacing="0" cellpadding="0" border="0" role="presentation" width="100%" align="left" class="r13-o" style="table-layout: fixed; width: 100%;"><tr><td align="left" valign="top" class="r12-i nl2go-default-textstyle" style="color: #3b3f44; font-family: Montserrat,arial,helvetica,sans-serif; font-size: 16px; line-height: 1.2; word-break: break-word; text-align: left;"> <div><div class="sib_class_16_black_b" style="color: #000; font-family: Montserrat,arial,helvetica,sans-serif; font-size: 16px; font-weight: 700; word-break: break-word;">Tax</div></div> </td> </tr></table></th> <th width="50%" valign="top" class="r39-c" style="font-weight: normal;"> <table cellspacing="0" cellpadding="0" border="0" role="presentation" width="100%" align="left" class="r13-o" style="table-layout: fixed; width: 100%;"><tr><td align="right" valign="top" class="r40-i nl2go-default-textstyle" style="color: #3b3f44; font-family: Montserrat,arial,helvetica,sans-serif; font-size: 16px; line-height: 1.2; word-break: break-word; text-align: right;"> <div><div class="sib_class_16_black_b" style="color: #000; font-family: Montserrat,arial,helvetica,sans-serif; font-size: 16px; font-weight: 700; word-break: break-word;">
  $${amount_tax / 100}
  </div></div> </td> </tr></table></th> </tr></table></td> </tr></table><table cellspacing="0" cellpadding="0" border="0" role="presentation" width="100%" align="center" class="r0-o" style="table-layout: fixed; width: 100%;"><tr><td class="r41-i" style="background-color: #fcf6ea; padding-left: 35px; padding-right: 35px; padding-top: 11px;"> <table width="100%" cellspacing="0" cellpadding="0" border="0" role="presentation"><tr><th width="50%" valign="top" class="r39-c" style="font-weight: normal;"> <table cellspacing="0" cellpadding="0" border="0" role="presentation" width="100%" align="left" class="r13-o" style="table-layout: fixed; width: 100%;"><tr><td align="left" valign="top" class="r12-i nl2go-default-textstyle" style="color: #3b3f44; font-family: Montserrat,arial,helvetica,sans-serif; font-size: 16px; line-height: 1.2; word-break: break-word; text-align: left;"> <div><div class="sib_class_16_black_b" style="color: #000; font-family: Montserrat,arial,helvetica,sans-serif; font-size: 16px; font-weight: 700; word-break: break-word;">Shipping fee</div></div> </td> </tr></table></th> <th width="50%" valign="top" class="r39-c" style="font-weight: normal;"> <table cellspacing="0" cellpadding="0" border="0" role="presentation" width="100%" align="left" class="r13-o" style="table-layout: fixed; width: 100%;"><tr><td align="right" valign="top" class="r40-i nl2go-default-textstyle" style="color: #3b3f44; font-family: Montserrat,arial,helvetica,sans-serif; font-size: 16px; line-height: 1.2; word-break: break-word; text-align: right;"> <div><div class="sib_class_16_black_b" style="color: #000; font-family: Montserrat,arial,helvetica,sans-serif; font-size: 16px; font-weight: 700; word-break: break-word;">
  $${amount_shipping / 100}
  </div></div> </td> </tr></table></th> </tr></table></td> </tr></table><table cellspacing="0" cellpadding="0" border="0" role="presentation" width="100%" align="center" class="r0-o" style="table-layout: fixed; width: 100%;"><tr><td class="r42-i" style="background-color: #fcf6ea; padding-left: 35px; padding-right: 35px; padding-top: 9px;"> <table width="100%" cellspacing="0" cellpadding="0" border="0" role="presentation"><tr><th width="100%" valign="top" class="r5-c" style="font-weight: normal;"> <table cellspacing="0" cellpadding="0" border="0" role="presentation" width="530" align="center" class="r0-o" style="table-layout: fixed;"><tr><td class="" style="height: 2px;"> <table width="100%" cellspacing="0" cellpadding="0" border="0" role="presentation"><tr><td><table width="100%" cellspacing="0" cellpadding="0" border="0" role="presentation" height="2" style="border-top-style: solid; background-clip: border-box; border-top-color: #5d695f; border-top-width: 2px; font-size: 2px; line-height: 2px;"><tr><td height="0" style="font-size: 0px; line-height: 0px;">­</td> </tr></table></td> </tr></table></td> </tr></table></th> </tr></table></td> </tr></table>
  <table cellspacing="0" cellpadding="0" border="0" role="presentation" width="100%" align="center" class="r0-o" style="table-layout: fixed; width: 100%;"><tr><td class="r43-i" style="background-color: #fcf6ea; padding-bottom: 55px; padding-left: 35px; padding-right: 35px; padding-top: 15px;"> <table width="100%" cellspacing="0" cellpadding="0" border="0" role="presentation"><tr><th width="50%" valign="top" class="r39-c" style="font-weight: normal;"> <table cellspacing="0" cellpadding="0" border="0" role="presentation" width="100%" align="left" class="r13-o" style="table-layout: fixed; width: 100%;"><tr><td align="left" valign="top" class="r12-i nl2go-default-textstyle" style="color: #3b3f44; font-family: Montserrat,arial,helvetica,sans-serif; font-size: 16px; line-height: 1.2; word-break: break-word; text-align: left;"> <div><div class="sib_class_20_black_b" style="color: #000; font-family: Montserrat,arial,helvetica,sans-serif; font-size: 20px; font-weight: 700; word-break: break-word;">TOTAL</div></div> </td> </tr></table></th> <th width="50%" valign="top" class="r39-c" style="font-weight: normal;"> <table cellspacing="0" cellpadding="0" border="0" role="presentation" width="100%" align="left" class="r13-o" style="table-layout: fixed; width: 100%;"><tr><td align="right" valign="top" class="r40-i nl2go-default-textstyle" style="color: #3b3f44; font-family: Montserrat,arial,helvetica,sans-serif; font-size: 16px; line-height: 1.2; word-break: break-word; text-align: right;"> <div><div class="sib_class_24_black_b" style="color: #000; font-family: Montserrat,arial,helvetica,sans-serif; font-size: 24px; font-weight: 700; word-break: break-word;">
  $${amount_total / 100}
  </div></div> </td> </tr></table></th> </tr></table></td> </tr></table>
  <table cellspacing="0" cellpadding="0" border="0" role="presentation" width="100%" align="center" class="r44-o" style="table-layout: fixed; width: 100%;"><tr><td class="r45-i" style="background-color: #976952; padding-left: 35px; padding-right: 35px; padding-top: 55px;"> <table width="100%" cellspacing="0" cellpadding="0" border="0" role="presentation"><tr><th width="100%" valign="top" class="r46-c" style="font-weight: normal;"> <table cellspacing="0" cellpadding="0" border="0" role="presentation" width="530" align="center" class="r0-o" style="table-layout: fixed; width: 530px;"><tr><td valign="top"> <table width="100%" cellspacing="0" cellpadding="0" border="0" role="presentation">
  <tr><td class="r48-c" style="display: inline-block;"> <table cellspacing="0" cellpadding="0" border="0" role="presentation" width="530" class="r6-o" style="table-layout: fixed; width: 530px;"><tr><td class="r49-i" style="padding-left: 213px; padding-right: 213px;"> 
  <table width="100%" cellspacing="0" cellpadding="0" border="0" role="presentation">
    <tr>
      <th width="52" class="r50-c mobshow resp-table" style="font-weight: normal;">
        <table cellspacing="0" cellpadding="0" border="0" role="presentation" width="100%" class="r51-o" style="table-layout: fixed; width: 100%;"><tr><td class="r52-i" style="font-size: 0px; line-height: 0px; padding-bottom: 5px; padding-top: 5px;"> <a href="https://www.tiktok.com/@terhireskin?is_from_webapp=1&sender_device=pc" target="_blank" style="color: #9c71f0; text-decoration: none;"><img src="https://res.cloudinary.com/diiohnshc/image/upload/v1712629206/Terhire/ot7cod8psxjmqlgaf4kx.png" width="32" border="0" style="display: block; width: 100%;"></a></td> <td class="nl2go-responsive-hide" width="20" style="font-size: 0px; line-height: 1px;">­ </td> </tr></table></th> <th width="52" class="r50-c mobshow resp-table" style="font-weight: normal;"> <table cellspacing="0" cellpadding="0" border="0" role="presentation" width="100%" class="r51-o" style="table-layout: fixed; width: 100%;"><tr><td class="r52-i" style="font-size: 0px; line-height: 0px; padding-bottom: 5px; padding-top: 5px;"> <a href="https://www.instagram.com/terhireskin?igsh=MW42d2x6enRyamt2OQ==" target="_blank" style="color: #9c71f0; text-decoration: none;"><img src="https://creative-assets.mailinblue.com/editor/social-icons/original_light/instagram_32px.png" width="32" border="0" style="display: block; width: 100%;"></a></td> <td class="nl2go-responsive-hide" width="20" style="font-size: 0px; line-height: 1px;">­ </td> </tr></table></th> </tr></table></td> </tr></table></td> </tr></table></td> </tr></table></th> </tr></table></td> </tr></table>
  <table cellspacing="0" cellpadding="0" border="0" role="presentation" width="100%" align="center" class="r0-o" style="table-layout: fixed; width: 100%;"><tr><td class="r53-i" style="background-color: #976952; padding-left: 35px; padding-right: 35px; padding-top: 48px;"> <table width="100%" cellspacing="0" cellpadding="0" border="0" role="presentation"><tr><th width="100%" valign="top" class="r5-c" style="font-weight: normal;"> <table cellspacing="0" cellpadding="0" border="0" role="presentation" width="100%" align="left" class="r13-o" style="table-layout: fixed; width: 100%;"><tr><td align="left" valign="top" class="r12-i nl2go-default-textstyle" style="color: #3b3f44; font-family: Montserrat,arial,helvetica,sans-serif; font-size: 16px; word-break: break-word; line-height: 1.3; text-align: left;"> <div><div class="sib_class_16_white_roboto" style="color: #fff; font-family: Montserrat,arial,helvetica,sans-serif; font-size: 16px; word-break: break-word;">Embrace the soothing essence of 'Terhire', a name inspired by my mother, and embark on a journey to discover the beauty of simplicity in skincare, where every small-batch product is carefully crafted with natural ingredients to offer deep hydration and a holistic, liberating experience for all skin types.</div></div> </td> </tr></table></th> </tr></table></td> </tr></table>
  <table cellspacing="0" cellpadding="0" border="0" role="presentation" width="100%" align="center" class="r44-o" style="table-layout: fixed; width: 100%;"><tr><td class="r54-i" style="background-color: #976952; padding-bottom: 45px; padding-left: 35px; padding-right: 150px; padding-top: 23px;"> <table width="100%" cellspacing="0" cellpadding="0" border="0" role="presentation"><tr><th width="20%" valign="top" class="r5-c" style="font-weight: normal;"> <table cellspacing="0" cellpadding="0" border="0" role="presentation" width="100%" align="left" class="r13-o" style="table-layout: fixed; width: 100%;"><tr><td align="left" valign="top" class="r12-i nl2go-default-textstyle" style="color: #3b3f44; font-family: Montserrat,arial,helvetica,sans-serif; font-size: 16px; line-height: 1.2; word-break: break-word; text-align: left;"> <div><div class="sib_class_16_white_roboto" style="color: #fff; font-family: Montserrat,arial,helvetica,sans-serif; font-size: 16px; word-break: break-word;"><a href="http://terhire.com/about" target="_blank" style="color: #9c71f0; text-decoration: none;"><span style="color: #ffffff;">About</span></a></div></div> </td> </tr></table></th> <th width="50%" valign="top" class="r5-c" style="font-weight: normal;"> <table cellspacing="0" cellpadding="0" border="0" role="presentation" width="100%" align="left" class="r13-o" style="table-layout: fixed; width: 100%;"><tr><td align="left" valign="top" class="r55-i nl2go-default-textstyle" style="color: #3b3f44; font-family: Montserrat,arial,helvetica,sans-serif; font-size: 16px; line-height: 1.2; word-break: break-word; text-align: left;"> <div><div class="sib_class_16_white_roboto" style="color: #fff; font-family: Montserrat,arial,helvetica,sans-serif; font-size: 16px; word-break: break-word;"><a href="http://terhire.com/faq" target="_blank" style="color: #9c71f0; text-decoration: none;"><span style="color: #ffffff;">FAQ</span></a></div></div> </td> </tr></table></th> </tr></table></td> </tr></table></td> </tr></table></td> </tr></table></body>
  </html>`;
};
export const subscriberEmailHtml = () => {
  return `
    <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
    <html xmlns="http://www.w3.org/1999/xhtml" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office">  
    <head>
      <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="format-detection" content="telephone=no">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title></title>      
      <style type="text/css" emogrify="no">#outlook a { padding:0; } .ExternalClass { width:100%; } .ExternalClass, .ExternalClass p, .ExternalClass span, .ExternalClass font, .ExternalClass td, .ExternalClass div { line-height: 100%; } table td { border-collapse: collapse; mso-line-height-rule: exactly; } .editable.image { font-size: 0 !important; line-height: 0 !important; } .nl2go_preheader { display: none !important; mso-hide:all !important; mso-line-height-rule: exactly; visibility: hidden !important; line-height: 0px !important; font-size: 0px !important; } body { width:100% !important; -webkit-text-size-adjust:100%; -ms-text-size-adjust:100%; margin:0; padding:0; } img { outline:none; text-decoration:none; -ms-interpolation-mode: bicubic; } a img { border:none; } table { border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; } th { font-weight: normal; text-align: left; } *[class="gmail-fix"] { display: none !important; } </style>      
      <style type="text/css" emogrify="no"> @media (max-width: 600px) { .gmx-killpill { content: ' /03D1';} } </style>
      <style type="text/css" emogrify="no">
        @media (max-width: 600px) {
           .gmx-killpill { content: ' /03D1';} 
           .r0-o { border-style: solid !important; margin: 0 auto 0 auto !important; width: 100% !important } 
           .r1-i { background-color: #5d695f !important } 
           .r2-c { box-sizing: border-box !important; text-align: center !important; valign: top !important; width: 320px !important } 
           .r3-o { border-style: solid !important; margin: 0 auto 0 auto !important; width: 450px !important } 
           .r4-i { padding-bottom: 31px !important; padding-left: 10px !important; padding-right: 10px !important; padding-top: 31px !important } 
           .r5-c { box-sizing: border-box !important; display: block !important; valign: top !important; width: 100% !important } 
           .r6-o { border-style: solid !important; width: 100% !important } 
           .r7-o { border-style: solid !important; margin: 0 auto 0 auto !important; width: 165px !important } 
           .r8-i { background-color: #5d695f !important } 
           .r9-c { box-sizing: border-box !important; text-align: center !important; valign: top !important; width: 100% !important } 
           .r10-i { background-color: #fcf6ea !important; padding-left: 15px !important; padding-right: 15px !important; padding-top: 76px !important } 
           .r11-o { border-style: solid !important; margin: 0 auto 0 0 !important; margin-bottom: 0px !important; margin-top: 0px !important; width: 100% !important } 
           .r12-i { text-align: left !important } 
           .r13-o { border-style: solid !important; margin: 0 auto 0 0 !important; width: 100% !important } 
           .r14-i { padding-top: 15px !important; text-align: left !important } 
           .r15-i { background-color: #fcf6ea !important; padding-bottom: 70px !important; padding-left: 15px !important; padding-right: 15px !important; padding-top: 45px !important } 
           .r16-i { padding-left: 0px !important; padding-right: 0px !important } 
           .r17-c { box-sizing: border-box !important; padding-top: 10px !important; text-align: left !important; valign: top !important; width: 100% !important } 
           .r18-c { box-sizing: border-box !important; padding: 0 !important; text-align: left !important; valign: top !important; width: 100% !important } 
           .r19-o { border-style: solid !important; margin: 0 auto 0 0 !important; margin-top: 40px !important; width: 100% !important } 
           .r20-i { padding: 0 !important; text-align: center !important } 
           .r21-r { background-color: #121212 !important; border-radius: 0px !important; border-width: 0px !important; box-sizing: border-box; height: initial !important; padding: 0 !important; padding-bottom: 14px !important; padding-left: 5px !important; padding-right: 5px !important; padding-top: 13px !important; text-align: center !important; width: 100% !important } 
           .r22-o { border-style: solid !important; margin: 0 auto 0 0 !important; margin-top: 20px !important; width: 100% !important } 
           .r23-r { background-color: #fcf6ea !important; border-color: #121212 !important; border-radius: 0px !important; border-width: 2px !important; box-sizing: border-box; height: initial !important; padding: 0 !important; padding-bottom: 12px !important; padding-left: 5px !important; padding-right: 5px !important; padding-top: 12px !important; text-align: center !important; width: 100% !important } 
           .r24-o { border-style: solid !important; margin: 0 0 0 auto !important; width: 100% !important } 
           .r25-i { padding-top: 30px !important } 
           .r26-i { background-color: #976952 !important; padding-bottom: 30px !important; padding-left: 15px !important; padding-right: 15px !important; padding-top: 30px !important } 
           .r27-i { padding-top: 20px !important; text-align: left !important } 
           .r28-i { background-color: #fcf6ea !important; padding-left: 10px !important; padding-right: 10px !important; padding-top: 57px !important } 
           .r29-c { box-sizing: border-box !important; text-align: center !important; valign: top !important; width: 124px !important } 
           .r30-o { border-style: solid !important; margin: 0 auto 0 auto !important; width: 124px !important } 
           .r31-c { box-sizing: border-box !important; text-align: left !important; valign: top !important; width: 100% !important } 
           .r32-o { border-style: solid !important; margin: 0 auto 0 0 !important; margin-top: 25px !important; width: 100% !important } 
           .r33-i { padding-top: 30px !important; text-align: center !important } 
           .r34-c { box-sizing: border-box !important; padding-top: 6px !important; text-align: center !important; valign: top !important; width: 100% !important } 
           .r35-i { padding-top: 20px !important; text-align: center !important } 
           .r36-i { background-color: #fcf6ea !important; padding-left: 10px !important; padding-right: 10px !important; padding-top: 30px !important } 
           .r37-i { background-color: #fcf6ea !important; padding-left: 15px !important; padding-right: 15px !important; padding-top: 30px !important } 
           .r38-i { background-color: #fcf6ea !important; padding-left: 15px !important; padding-right: 15px !important; padding-top: 18px !important } 
           .r39-c { box-sizing: border-box !important; valign: top !important; width: 50% !important } 
           .r40-i { text-align: right !important } 
           .r41-i { background-color: #fcf6ea !important; padding-left: 15px !important; padding-right: 15px !important; padding-top: 11px !important } 
           .r42-i { background-color: #fcf6ea !important; padding-left: 15px !important; padding-right: 15px !important; padding-top: 9px !important } 
           .r43-i { background-color: #fcf6ea !important; padding-bottom: 55px !important; padding-left: 15px !important; padding-right: 15px !important; padding-top: 15px !important } 
           .r44-o { background-size: cover !important; border-style: solid !important; margin: 0 auto 0 auto !important; width: 100% !important } 
           .r45-i { background-color: #976952 !important; padding-left: 15px !important; padding-right: 15px !important; padding-top: 55px !important } 
           .r46-c { box-sizing: border-box !important; valign: top !important; width: 100% !important } 
           .r47-c { box-sizing: border-box !important; text-align: center !important; width: 100% !important } 
           .r48-c { box-sizing: border-box !important; width: 100% !important } 
           .r49-i { font-size: 0px !important; padding-left: 93px !important; padding-right: 93px !important } 
           .r50-c { box-sizing: border-box !important; width: 32px !important } 
           .r51-o { border-style: solid !important; margin-right: 20px !important; width: 32px !important } 
           .r52-i { padding-bottom: 5px !important; padding-top: 5px !important } 
           .r53-i { background-color: #976952 !important; padding-left: 15px !important; padding-right: 15px !important; padding-top: 48px !important } 
           .r54-i { background-color: #976952 !important; padding-bottom: 45px !important; padding-left: 15px !important; padding-right: 15px !important; padding-top: 23px !important } 
           .r55-i { padding-top: 5px !important; text-align: left !important } body { -webkit-text-size-adjust: none } 
           .nl2go-responsive-hide { display: none } 
           .nl2go-body-table { min-width: unset !important } 
           .mobshow { height: auto !important; overflow: visible !important; max-height: unset !important; visibility: visible !important; border: none !important } 
           .resp-table { display: inline-table !important } 
           .magic-resp { display: table-cell !important } 
          } 
      </style>
      <!--[if !mso]><!-->
      <style type="text/css" emogrify="no">@import url("https://fonts.googleapis.com/css2?family=Montserrat"); </style>
      <!--<![endif]-->
      <style type="text/css">
        p, h1, h2, h3, h4, ol, ul, li { margin: 0; } 
        a, a:link { color: #9c71f0; text-decoration: none } 
        .nl2go-default-textstyle { color: #3b3f44; font-family: Montserrat, arial,helvetica,sans-serif; font-size: 16px; line-height: 1.2; word-break: break-word } 
        .default-button { color: #3b3f44; font-family: Montserrat, arial,helvetica,sans-serif; font-size: 16px; font-style: normal; font-weight: normal; line-height: 1.15; text-decoration: none; word-break: break-word } 
        .sib_class_16_white_roboto { color: #FFFFFF; font-family: Montserrat, arial,helvetica,sans-serif; font-size: 16px; word-break: break-word } 
        .sib_class_16_black { color: #000000; font-family: Montserrat, arial,helvetica,sans-serif; font-size: 16px; word-break: break-word } 
        .sib_class_16_white { color: #ffffff; font-family: Montserrat, arial,helvetica,sans-serif; font-size: 16px; word-break: break-word } 
        .sib_class_16_black_sb { color: #000000; font-family: Montserrat, arial,helvetica,sans-serif; font-size: 16px; font-weight: 600; word-break: break-word } 
        .sib_class_16_black_b { color: #000000; font-family: Montserrat, arial,helvetica,sans-serif; font-size: 16px; font-weight: 700; word-break: break-word } 
        .sib_class_18_black_sb { color: #000000; font-family: Montserrat, arial,helvetica,sans-serif; font-size: 18px; font-weight: 600; word-break: break-word } 
        .sib_class_18_blue_sb { color: #75EBEF; font-family: Montserrat, arial,helvetica,sans-serif; font-size: 18px; font-weight: 600; word-break: break-word } 
        .sib_class_20_black_roboto { color: #000000; font-family: Montserrat, arial,helvetica,sans-serif; font-size: 20px; word-break: break-word } 
        .sib_class_20_black_b { color: #000000; font-family: Montserrat, arial,helvetica,sans-serif; font-size: 20px; font-weight: 700; word-break: break-word } 
        .sib_class_20_black_b_ul { color: #000000; font-family: Montserrat, arial,helvetica,sans-serif; font-size: 20px; font-weight: 700; text-decoration: underline; word-break: break-word } 
        .sib_class_20_white_b_ul { color: #ffffff; font-family: Montserrat, arial,helvetica,sans-serif; font-size: 20px; font-weight: 700; text-decoration: underline; word-break: break-word } 
        .sib_class_24_black_b { color: #000000; font-family: Montserrat, arial,helvetica,sans-serif; font-size: 24px; font-weight: 700; word-break: break-word } 
        .sib_class_30_black_sb { color: #000000; font-family: Montserrat, arial,helvetica,sans-serif; font-size: 30px; font-weight: 600; word-break: break-word } 
        .default-heading1 { color: #000000; font-family: Montserrat, arial,helvetica,sans-serif; font-size: 30px; word-break: break-word } 
        .default-heading2 { color: #ffffff; font-family: Montserrat, arial,helvetica,sans-serif; font-size: 20px; word-break: break-word } 
        .default-heading3 { color: #000000; font-family: Montserrat, arial,helvetica,sans-serif; font-size: 20px; word-break: break-word } 
        .default-heading4 { color: #000000; font-family: Montserrat, arial,helvetica,sans-serif; font-size: 18px; word-break: break-word } 
        a[x-apple-data-detectors] { color: inherit !important; text-decoration: inherit !important; font-size: inherit !important; font-family: inherit !important; font-weight: inherit !important; line-height: inherit !important; } 
        .no-show-for-you { border: none; display: none; float: none; font-size: 0; height: 0; line-height: 0; max-height: 0; mso-hide: all; overflow: hidden; table-layout: fixed; visibility: hidden; width: 0; } 
      </style>
      <!--[if mso]><xml> 
      <o:OfficeDocumentSettings> <o:AllowPNG/> 
      <o:PixelsPerInch>96</o:PixelsPerInch> </o:OfficeDocumentSettings> 
      </xml><![endif]-->
      <style type="text/css">a:link{color: #9c71f0; text-decoration: none;}
      </style>
    </head>      
    <body bgcolor="#9c71f0" text="#3b3f44" link="#9c71f0" yahoo="fix" style="background-color: #5d695f;">
      <table cellspacing="0" cellpadding="0" border="0" role="presentation" class="nl2go-body-table" width="100%" style="background-color: #5d695f; width: 100%;">
      <tr><td> <table cellspacing="0" cellpadding="0" border="0" role="presentation" width="100%" align="center" class="r0-o" style="table-layout: fixed; width: 100%;"><tr><td valign="top" class="r1-i" style="background-color: #5d695f;"> <table cellspacing="0" cellpadding="0" border="0" role="presentation" width="600" align="center" class="r3-o" style="table-layout: fixed; width: 600px;"><tr><td class="r4-i" style="padding-bottom: 31px; padding-left: 10px; padding-right: 10px; padding-top: 31px;"> <table width="100%" cellspacing="0" cellpadding="0" border="0" role="presentation"><tr><th width="100%" valign="top" class="r5-c" style="font-weight: normal;"> <table cellspacing="0" cellpadding="0" border="0" role="presentation" width="165" align="center" class="r7-o" style="table-layout: fixed; width: 165px;"><tr><td style="font-size: 0px; line-height: 0px;"> <a href="https://terhire.com" target="_blank" style="color: #9c71f0; text-decoration: none;"><img src="https://res.cloudinary.com/diiohnshc/image/upload/v1712400750/Terhire/Terhire_1_fb9bju.png" width="165" border="0" style="display: block; width: 100%;"></td> </tr></table></th> </tr></table></td> </tr></table></td> </tr></table>
      
      
  <table cellspacing="0" cellpadding="0" border="0" role="presentation" width="600" align="center" class="r3-o" style="table-layout: fixed; width: 600px;"><tr><td valign="top" class="r8-i" style="background-color: #9c71f0;"> <table cellspacing="0" cellpadding="0" border="0" role="presentation" width="100%" align="center" class="r0-o" style="table-layout: fixed; width: 100%;"><tr><td class="r10-i" style="background-color: #fcf6ea; padding-bottom: 30px; padding-left: 35px; padding-right: 35px; padding-top: 30px;"> <table width="100%" cellspacing="0" cellpadding="0" border="0" role="presentation"><tr><th width="100%" valign="top" class="r5-c" style="font-weight: normal;"> <table cellspacing="0" cellpadding="0" border="0" role="presentation" width="65%" align="center" class="r11-o" style="table-layout: fixed; width: 65%;"><tr><td align="center" valign="top" class="r12-i nl2go-default-textstyle" style="color: #3b3f44; font-family: Montserrat,arial,helvetica,sans-serif; font-size: 16px; line-height: 1.2; word-break: break-word; text-align: center;"> <div><h1 class="default-heading1" style="margin: 0; color: #000; font-family: Montserrat,arial,helvetica,sans-serif; font-size: 30px; word-break: break-word;"><span style="font-size: 32px;">YOUR WELCOME GIFT AWAITS </span></h1></div> </td> </tr></table></th> </tr></table></td> </tr></table>
  <table cellspacing="0" cellpadding="0" border="0" role="presentation" width="100%" align="center" class="r11-o" style="table-layout: fixed; width: 100%;"><tr><td class="r13-i" style="background-color: #fcf6ea;"> <table width="100%" cellspacing="0" cellpadding="0" border="0" role="presentation"><tr><th width="100%" valign="top" class="r5-c" style="background-color: #fcf6ea; font-weight: normal;"> <table cellspacing="0" cellpadding="0" border="0" role="presentation" width="100%" class="r14-o" style="table-layout: fixed; width: 100%;"><tr><td valign="top" class="r15-i" style="background-color: #fcf6ea; padding-left: 15px; padding-right: 15px;"> <table width="100%" cellspacing="0" cellpadding="0" border="0" role="presentation"><tr><td class="r16-c" align="center" style="border-radius: 8px; font-size: 0px; line-height: 0px; valign: top;"> <img src="https://res.cloudinary.com/diiohnshc/image/upload/v1712680168/Photoroom_20240402_220050_rnmilf.jpg" width="570" border="0" style="display: block; width: 100%; border-radius: 8px;"></td> </tr><tr><td class="r17-c" align="left"> <table cellspacing="0" cellpadding="0" border="0" role="presentation" width="100%" class="r18-o" style="table-layout: fixed; width: 100%;"><tr class="nl2go-responsive-hide"><td height="15" style="font-size: 15px; line-height: 15px;">­</td> </tr><tr><td align="center" valign="top" class="r19-i nl2go-default-textstyle" style="color: #3b3f44; font-family: Montserrat,arial,helvetica,sans-serif; font-size: 16px; line-height: 1.2; word-break: break-word; text-align: center;"> <div><p style="margin: 0;">We're excited to have you on board. Now that you've joined our community, we'd like to offer you 10% off your first order. Enter the code <strong>WELCOME10T </strong>at online checkout.</p></div> </td> </tr><tr class="nl2go-responsive-hide"><td height="15" style="font-size: 15px; line-height: 15px;">­</td> </tr></table></td> </tr>
  <tr><td class="r20-c" align="center" style="align: center; padding-bottom: 10px; padding-top: 0px; valign: top;"> <table cellspacing="0" cellpadding="0" border="0" role="presentation" width="160" class="r21-o" style="background-color: #5d695f; border-collapse: separate; border-color: #666666; border-radius: 0px; border-style: solid; border-width: 0px; table-layout: fixed; width: 160px;"><tr><td height="18" align="center" valign="top" class="r22-i nl2go-default-textstyle" style="color: #3b3f44; font-family: Montserrat,arial,helvetica,sans-serif; font-size: 16px; word-break: break-word; background-color: #5d695f; border-radius: 0px; font-style: normal; line-height: 1.15; padding-bottom: 12px; padding-left: 0px; padding-right: 0px; padding-top: 12px; text-align: center;"> <a href="https://terhire.com/collections" class="r23-r default-button" target="_blank" data-btn="1" style="color: #3b3f44; font-family: Montserrat,arial,helvetica,sans-serif; font-size: 16px; font-style: normal; font-weight: normal; line-height: 1.15; text-decoration: none; word-break: break-word; word-wrap: break-word; display: block; -webkit-text-size-adjust: none;"> <span><span style="color: #FFFFFF;"><strong>SHOP NOW</strong></span></span></a> </td> </tr></table></td> </tr></table></td> </tr></table></th> </tr></table></td> </tr></table>

  <table cellspacing="0" cellpadding="0" border="0" role="presentation" width="100%" align="center" class="r44-o" style="table-layout: fixed; width: 100%;"><tr><td class="r45-i" style="background-color: #976952; padding-left: 35px; padding-right: 35px; padding-top: 55px;"> <table width="100%" cellspacing="0" cellpadding="0" border="0" role="presentation"><tr><th width="100%" valign="top" class="r46-c" style="font-weight: normal;"> <table cellspacing="0" cellpadding="0" border="0" role="presentation" width="530" align="center" class="r0-o" style="table-layout: fixed; width: 530px;"><tr><td valign="top"> <table width="100%" cellspacing="0" cellpadding="0" border="0" role="presentation">
  <tr><td class="r48-c" style="display: inline-block;"> <table cellspacing="0" cellpadding="0" border="0" role="presentation" width="530" class="r6-o" style="table-layout: fixed; width: 530px;"><tr><td class="r49-i" style="padding-left: 213px; padding-right: 213px;"> <table width="100%" cellspacing="0" cellpadding="0" border="0" role="presentation"><tr>
    <th width="52" class="r50-c mobshow resp-table" style="font-weight: normal;"> <table cellspacing="0" cellpadding="0" border="0" role="presentation" width="100%" class="r51-o" style="table-layout: fixed; width: 100%;"><tr><td class="r52-i" style="font-size: 0px; line-height: 0px; padding-bottom: 5px; padding-top: 5px;"> <a href="https://www.tiktok.com/@terhireskin?is_from_webapp=1&sender_device=pc" target="_blank" style="color: #9c71f0; text-decoration: none;"><img src="https://res.cloudinary.com/diiohnshc/image/upload/v1712629206/Terhire/ot7cod8psxjmqlgaf4kx.png" width="32" border="0" style="display: block; width: 100%;"></a></td> <td class="nl2go-responsive-hide" width="20" style="font-size: 0px; line-height: 1px;">­ </td> </tr></table></th> 
    <th width="52" class="r50-c mobshow resp-table" style="font-weight: normal;"> <table cellspacing="0" cellpadding="0" border="0" role="presentation" width="100%" class="r51-o" style="table-layout: fixed; width: 100%;"><tr><td class="r52-i" style="font-size: 0px; line-height: 0px; padding-bottom: 5px; padding-top: 5px;"> <a href="https://www.instagram.com/terhireskin?igsh=MW42d2x6enRyamt2OQ==" target="_blank" style="color: #9c71f0; text-decoration: none;"><img src="https://creative-assets.mailinblue.com/editor/social-icons/original_light/instagram_32px.png" width="32" border="0" style="display: block; width: 100%;"></a></td> <td class="nl2go-responsive-hide" width="20" style="font-size: 0px; line-height: 1px;">­ </td> </tr></table></th> </tr></table></td> </tr></table></td> </tr></table></td> </tr></table></th> </tr></table></td> </tr></table>
  <table cellspacing="0" cellpadding="0" border="0" role="presentation" width="100%" align="center" class="r0-o" style="table-layout: fixed; width: 100%;"><tr><td class="r53-i" style="background-color: #976952; padding-left: 35px; padding-right: 35px; padding-top: 48px;"> <table width="100%" cellspacing="0" cellpadding="0" border="0" role="presentation"><tr><th width="100%" valign="top" class="r5-c" style="font-weight: normal;"> <table cellspacing="0" cellpadding="0" border="0" role="presentation" width="100%" align="left" class="r13-o" style="table-layout: fixed; width: 100%;"><tr><td align="left" valign="top" class="r12-i nl2go-default-textstyle" style="color: #3b3f44; font-family: Montserrat,arial,helvetica,sans-serif; font-size: 16px; word-break: break-word; line-height: 1.3; text-align: left;"> <div><div class="sib_class_16_white_roboto" style="color: #fff; font-family: Montserrat,arial,helvetica,sans-serif; font-size: 16px; word-break: break-word;">Embrace the soothing essence of 'Terhire', a name inspired by my mother, and embark on a journey to discover the beauty of simplicity in skincare, where every small-batch product is carefully crafted with natural ingredients to offer deep hydration and a holistic, liberating experience for all skin types.</div></div> </td> </tr></table></th> </tr></table></td> </tr></table>
  <table cellspacing="0" cellpadding="0" border="0" role="presentation" width="100%" align="center" class="r44-o" style="table-layout: fixed; width: 100%;"><tr><td class="r54-i" style="background-color: #976952; padding-bottom: 45px; padding-left: 35px; padding-right: 150px; padding-top: 23px;"> <table width="100%" cellspacing="0" cellpadding="0" border="0" role="presentation"><tr><th width="20%" valign="top" class="r5-c" style="font-weight: normal;"> <table cellspacing="0" cellpadding="0" border="0" role="presentation" width="100%" align="left" class="r13-o" style="table-layout: fixed; width: 100%;"><tr><td align="left" valign="top" class="r12-i nl2go-default-textstyle" style="color: #3b3f44; font-family: Montserrat,arial,helvetica,sans-serif; font-size: 16px; line-height: 1.2; word-break: break-word; text-align: left;"> <div><div class="sib_class_16_white_roboto" style="color: #fff; font-family: Montserrat,arial,helvetica,sans-serif; font-size: 16px; word-break: break-word;"><a href="http://terhire.com/about" target="_blank" style="color: #9c71f0; text-decoration: none;"><span style="color: #ffffff;">About</span></a></div></div> </td> </tr></table></th> <th width="50%" valign="top" class="r5-c" style="font-weight: normal;"> <table cellspacing="0" cellpadding="0" border="0" role="presentation" width="100%" align="left" class="r13-o" style="table-layout: fixed; width: 100%;"><tr><td align="left" valign="top" class="r55-i nl2go-default-textstyle" style="color: #3b3f44; font-family: Montserrat,arial,helvetica,sans-serif; font-size: 16px; line-height: 1.2; word-break: break-word; text-align: left;"> <div><div class="sib_class_16_white_roboto" style="color: #fff; font-family: Montserrat,arial,helvetica,sans-serif; font-size: 16px; word-break: break-word;"><a href="http://terhire.com/faq" target="_blank" style="color: #9c71f0; text-decoration: none;"><span style="color: #ffffff;">FAQ</span></a></div></div> </td> </tr></table></th> </tr></table></td> </tr></table></td> </tr></table></td> </tr></table></body>
  </html>`;
};
